name: Test, Build, and Deploy | Modul 01 - Lab2.2 Senior Project

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
          cache: "npm"
      - run: npm i
      - run: npm run build

  deploy:
    needs: test-build
    runs-on: ubuntu-latest

    strategy: 
      matrix: 
        node-version: [16.x]

    steps:
      - name: Build app on VM
        uses: appeboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDT4cGQA9fy5MTZB754w+8oyKYd5rw9SuRw9WO4LfYFySr8p07f/rqCVm0EQB6vYHL+5fBpgY0TJpbhg0WyD3GMtCK1REfIVoZP0Dl9MYjCcVRiwQ1LjJm9SQ5ylvB+/6gCeunQKJu+6Tsw3TR/9myEgxsruK7rzAHx84psH6G83xWOlPqRY7zyv3yeEcnxqKjCyntTPLs7IZf/tHSEHmZgzicOdqBwVnDbwQltm5ZN06csRAOvc7vL98fn7KogGKLAmVXRqBsQ0ZuUss65sF0rOoa0Dm1LjcJ06DX+/ipoF6YmNzGjY4yW40DhXbTpOg2P94MyBgiUGMWRJcZr4bIjyKfHj5ShOyCoqBFRO5l9ynPghyFH0/GdB6RMQMX8Xu4q1AlB6bqmH19EbIrfiZwno0aAaVik6fZ7THH7uRC7ONTFmMoCGoq+s5osn8vsmilzsrG/pl9q3105GJSQ8HTHwfJMm3eiRLEih79ox0LIeizIWzMb+hgXWP1JcwEvyirrYuo8tKMd5E+bFCvTX3WxyiSPTEH/9QH6+xSi3sIZ3C8Enq0+qycE1gTSnL4QWyff+TkjTHxztNI4hAJeempB7MmYM3ieNnw6Us54WCjnVPmvvO/dhLrfm71QAuzAGSmCzdE3lCum7A1yniTwe/JKfY4PE7gu3ca1Oc8t+fDy+w== Praktikan26
            echo "Cek folder project";
            [ ! -d "${HOME}/senpro/senpro/538937/modul02/senpro-github-action/" ] &&
              {
                echo "Repository belum di-clone. Cloning...";
                mkdir -p ~/senpro/538937/modul02;
                cd ~/senpro/538937/modul02;
                git clone https://github.com/olannora/senpro-github-action;
                cd ~/senpro/538937/modul02/senpro-github-action;
                echo "Install Package and Build Project";
                npm install;
                npm run build;
              } ||
              {
                echo "Repository sudah ada. Building...";
                cd ~/senpro/538937/modul02/senpro-github-action;
                git restore .;
                git pull origin main;
                echo "Install Package and Build Project";
                npm install;
                npm run build;
              }